### ISSUE TITLE
support pygments >= 2.7.1

### ISSUE THREAD

**Issue by sandrotosi** [tmm1/pygments.rb#195]
Hello,
in debian we recently upgraded pygments to 2.7.1 and pygments.rb started to show these errors when running tests:

```
  test_highlight_works_with_larger_files:               F
===============================================================================
Failure: test_highlight_works_with_larger_files(PygmentsHighlightTest)
/build/ruby-pygments.rb-1.2.1/test/test_pygments.rb:38:in `test_highlight_works_with_larger_files'
     35:   def test_highlight_works_with_larger_files
     36:     code = P.highlight(REDIS_CODE)
     37:     assert_match 'used_memory_peak_human', code
  => 38:     assert_equal 458511, code.bytesize.to_i
     39:   end
     40:
     41:   def test_highlight_works_with_null_bytes
<458511> expected but was
<462036>

diff:
? 458511
?  62036
===============================================================================
: (0.242569)
```

and

```
  test_highlight_works_with_single_character_input:     F
===============================================================================
Failure: test_highlight_works_with_single_character_input(PygmentsHighlightTest):
  </a\n<\/pre>/> was expected to be =~
  <"<div class=\"highlight\"><pre><span></span><span class=\"err\">a</span>\n" +
  "</pre></div>">.
/build/ruby-pygments.rb-1.2.1/test/test_pygments.rb:89:in `test_highlight_works_with_single_character_input'
     86:
     87:   def test_highlight_works_with_single_character_input
     88:     code = P.highlight("a")
  => 89:     assert_match "a\n</pre>", code
     90:   end
     91:
     92:   def test_highlight_works_with_trailing_newline
===============================================================================
: (0.019281)
```

can you have a look at this and release a fix? this will help debian greatly.

thanks!

**Comment by dleidert** [comment]
A fellow Debian developer wrote a patch to address this issue:
<https://bugs.debian.org/cgi-bin/bugreport.cgi?att=4;bug=972481;filename=0004-Make-the-test-less-dependent-on-the-pygments-version.patch;msg=12>
